"""
All assessment content lives here so app.py stays clean.

QUESTIONS: 95 Likert items with their 5 response options each
DEMOGRAPHICS: 5 intake fields
REVERSE_CODED_ITEMS: Set of question IDs (e.g., "Q3") that need score inversion
SCORING_RUBRIC: Subdomain mapping with low/medium/high thresholds
"""

DEMOGRAPHICS = [
    {"id": "name", "label": "Name (optional)", "type": "text", "required": False},
    {"id": "age", "label": "Age", "type": "number", "required": True, "min": 16, "max": 99},
    {"id": "gender", "label": "Gender", "type": "select", "required": True,
     "options": ["Male", "Female", "Other", "Prefer not to say"]},
    {"id": "job_role", "label": "Job / Role", "type": "text", "required": True},
    {"id": "years_experience", "label": "Years of Experience", "type": "text", "required": True},
]

# Reverse-coded items (marked with * in the original document)
REVERSE_CODED_ITEMS = {
    "Q3", "Q10", "Q37", "Q45", "Q66", "Q72", "Q73", "Q74",
    "Q75", "Q76", "Q81", "Q88", "Q89", "Q92", "Q93", "Q94"
}


# Question definitions grouped by section
QUESTIONS = [
    {
        "section": "1. Well-being & Stress",
        "description": "How you experience stress, workload, recovery, and well-being at work.",
        "items": [
            {"id": "Q1", "text": "How often do you feel overwhelmed by the demands of your work or personal life?",
             "options": ["Never","Rarely","Sometimes","Often","Very Often"]},
            {"id": "Q2", "text": "In the past month, how frequently have you felt mentally exhausted or unable to \u201Cswitch off\u201D from stress?",
             "options": ["Not at all","Rarely","Sometimes","Frequently","Extremely often"]},
            {"id": "Q3", "text": "When stress increases, how confident do you feel in handling it effectively?",
             "options": ["Not confident at all","Slightly confident","Moderately confident","Very confident","Extremely confident"]},
            {"id": "Q4", "text": "How often do you feel emotionally drained after completing your workday?",
             "options": ["Never","Rarely","Sometimes","Often","Very Often"]},
            {"id": "Q5", "text": "How difficult is it for you to recover or feel refreshed after work-related stress?",
             "options": ["Not difficult at all","Slightly difficult","Moderately difficult","Very difficult","Extremely difficult"]},
            {"id": "Q6", "text": "How frequently do deadlines make you feel pressured or rushed at work?",
             "options": ["Never","Rarely","Sometimes","Often","Extremely often"]},
            {"id": "Q7", "text": "How manageable are your daily work tasks and expectations?",
             "options": ["Completely manageable","Mostly manageable","Moderately manageable","Difficult to manage","Completely unmanageable"]},
            {"id": "Q8", "text": "How difficult is it for you to disconnect from work during personal time?",
             "options": ["Not difficult at all","Slightly difficult","Moderately difficult","Very difficult","Extremely difficult"]},
            {"id": "Q9", "text": "How sufficient are your breaks, weekends, or leave periods for helping you recover from work stress?",
             "options": ["Not sufficient at all","Slightly sufficient","Moderately sufficient","Very sufficient","Completely sufficient"]},
            {"id": "Q10", "text": "How frequently do you feel physically or mentally fatigued before the workday ends?",
             "options": ["Never","Rarely","Sometimes","Frequently","Very frequently"]},
            {"id": "Q11", "text": "How confident are you in handling stressful situations at work?",
             "options": ["Not confident at all","Slightly confident","Moderately confident","Very confident","Extremely confident"]},
            {"id": "Q12", "text": "How quickly do you feel able to recover after a stressful work experience or setback?",
             "options": ["Very slowly","Slowly","Moderately quickly","Quickly","Very quickly"]},
            {"id": "Q13", "text": "How often does work-related stress affect your sleep?",
             "options": ["Never","Rarely","Sometimes","Often","Very Often"]},
            {"id": "Q14", "text": "Do work demands affect the number of hours you sleep?",
             "options": ["Never","Rarely","Sometimes","Often","Very Often"]},
            {"id": "Q15", "text": "How accessible are mental health or wellness resources within your workplace?",
             "options": ["Not accessible at all","Slightly accessible","Moderately accessible","Very accessible","Extremely accessible"]},
            {"id": "Q16", "text": "Do you believe your workplace takes employee well-being seriously?",
             "options": ["Strongly No","No","Neutral","Yes","Strongly Yes"]},
            {"id": "Q17", "text": "How supported do you feel by supervisors or colleagues during stressful periods?",
             "options": ["Not supported at all","Slightly supported","Moderately supported","Very supported","Extremely supported"]},
        ],
    },
    {
        "section": "2. Job Satisfaction",
        "description": "Satisfaction with role, compensation, environment, and growth opportunities.",
        "items": [
            {"id": "Q18", "text": "Do you feel your work contributes positively to something important?",
             "options": ["Strongly No","No","Neutral","Yes","Strongly Yes"]},
            {"id": "Q19", "text": "How satisfied are you with the impact your work creates?",
             "options": ["Very dissatisfied","Dissatisfied","Neutral","Satisfied","Very satisfied"]},
            {"id": "Q20", "text": "How satisfied are you with your current salary and benefits?",
             "options": ["Very dissatisfied","Dissatisfied","Neutral","Satisfied","Very satisfied"]},
            {"id": "Q21", "text": "Do you feel your compensation fairly reflects your work and responsibilities?",
             "options": ["Strongly No","No","Neutral","Yes","Strongly Yes"]},
            {"id": "Q22", "text": "How often do you feel appreciated for the work you do?",
             "options": ["Never","Rarely","Sometimes","Often","Very Often"]},
            {"id": "Q23", "text": "How satisfied are you with the feedback or acknowledgment you receive at work?",
             "options": ["Very dissatisfied","Dissatisfied","Neutral","Satisfied","Very satisfied"]},
            {"id": "Q24", "text": "How well does your current job match your skills and abilities?",
             "options": ["Very poorly","Poorly","Moderately","Well","Very well"]},
            {"id": "Q25", "text": "How interested do you feel in your daily work tasks?",
             "options": ["Not interested at all","Slightly interested","Moderately interested","Very interested","Extremely interested"]},
            {"id": "Q26", "text": "How often do you feel your strengths are effectively used in your role?",
             "options": ["Never","Rarely","Sometimes","Often","Very Often"]},
            {"id": "Q27", "text": "How positively would you describe the culture of your workplace?",
             "options": ["Very negative","Negative","Neutral","Positive","Very positive"]},
            {"id": "Q28", "text": "How effectively does your team collaborate and communicate?",
             "options": ["Very poorly","Poorly","Moderately","Effectively","Very effectively"]},
            {"id": "Q29", "text": "How comfortable do you feel interacting with colleagues at work?",
             "options": ["Very uncomfortable","Uncomfortable","Neutral","Comfortable","Very comfortable"]},
            {"id": "Q30", "text": "How supported do you feel by your immediate supervisor or manager?",
             "options": ["Not supported at all","Slightly supported","Moderately supported","Very supported","Extremely supported"]},
            {"id": "Q31", "text": "How respectfully are you treated by your supervisor?",
             "options": ["Very disrespectfully","Disrespectfully","Neutral","Respectfully","Very respectfully"]},
            {"id": "Q32", "text": "How much freedom do you have in deciding how to complete your work?",
             "options": ["No freedom","Little freedom","Moderate freedom","High freedom","Complete freedom"]},
            {"id": "Q33", "text": "How satisfied are you with the level of independence you have at work?",
             "options": ["Very dissatisfied","Dissatisfied","Neutral","Satisfied","Very satisfied"]},
            {"id": "Q34", "text": "How satisfied are you with your opportunities for career growth in this organization?",
             "options": ["Very dissatisfied","Dissatisfied","Neutral","Satisfied","Very satisfied"]},
            {"id": "Q35", "text": "How optimistic are you about your future career progression here?",
             "options": ["Not optimistic","Slightly optimistic","Moderately optimistic","Very optimistic","Extremely optimistic"]},
            {"id": "Q36", "text": "How fairly do you think promotions or advancement opportunities are provided?",
             "options": ["Very unfairly","Unfairly","Neutral","Fairly","Very fairly"]},
        ],
    },
    {
        "section": "3. Engagement & Motivation",
        "description": "Your engagement, drive, and emotional connection to work.",
        "items": [
            {"id": "Q37", "text": "How easily do you lose concentration while working?",
             "options": ["Never","Rarely","Sometimes","Frequently","Very frequently"]},
            {"id": "Q38", "text": "How willing are you to put in extra effort to achieve work goals when needed?",
             "options": ["Not willing at all","Slightly willing","Moderately willing","Very willing","Extremely willing"]},
            {"id": "Q39", "text": "How strongly do you believe in the goals set by your organization or team?",
             "options": ["Not at all","Slightly","Moderately","Strongly","Very strongly"]},
            {"id": "Q40", "text": "Do you enjoy your work even without external rewards or recognition?",
             "options": ["Strongly No","No","Neutral","Yes","Strongly Yes"]},
            {"id": "Q41", "text": "How strongly do rewards such as salary, promotion, or recognition motivate you at work?",
             "options": ["Not motivating at all","Slightly motivating","Moderately motivating","Very motivating","Extremely motivating"]},
            {"id": "Q42", "text": "How often do you take initiative beyond your assigned responsibilities?",
             "options": ["Never","Rarely","Sometimes","Often","Very Often"]},
            {"id": "Q43", "text": "How comfortable are you acting without waiting for instructions when necessary?",
             "options": ["Very uncomfortable","Uncomfortable","Neutral","Comfortable","Very comfortable"]},
            {"id": "Q44", "text": "How willing are you to take ownership of challenges at work?",
             "options": ["Not willing at all","Slightly willing","Moderately willing","Very willing","Extremely willing"]},
            {"id": "Q45", "text": "How often do you feel like giving up on difficult work tasks?",
             "options": ["Never","Rarely","Sometimes","Often","Very Often"]},
            {"id": "Q46", "text": "How determined are you to complete tasks even under challenging conditions?",
             "options": ["Not determined at all","Slightly determined","Moderately determined","Very determined","Extremely determined"]},
            {"id": "Q47", "text": "How proud do you feel to be associated with your organization?",
             "options": ["Not proud at all","Slightly proud","Moderately proud","Very proud","Extremely proud"]},
            {"id": "Q48", "text": "How comfortable do you feel sharing ideas or suggestions at work?",
             "options": ["Very uncomfortable","Uncomfortable","Neutral","Comfortable","Very comfortable"]},
            {"id": "Q49", "text": "Do your personal values align with the goals of your organization?",
             "options": ["Strongly No","No","Neutral","Yes","Strongly Yes"]},
        ],
    },
    {
        "section": "4. Growth & Opportunity",
        "description": "Learning, career development, and growth opportunities.",
        "items": [
            {"id": "Q50", "text": "How satisfied are you with the learning and training opportunities available in your workplace?",
             "options": ["Very dissatisfied","Dissatisfied","Neutral","Satisfied","Very satisfied"]},
            {"id": "Q51", "text": "Do you feel your job helps you develop new knowledge or skills?",
             "options": ["Strongly No","No","Neutral","Yes","Strongly Yes"]},
            {"id": "Q52", "text": "How accessible are workshops, training, or learning resources in your organization?",
             "options": ["Not accessible at all","Slightly accessible","Moderately accessible","Very accessible","Extremely accessible"]},
            {"id": "Q53", "text": "How confident are you about your chances for promotion or advancement in this organization?",
             "options": ["Not confident at all","Slightly confident","Moderately confident","Very confident","Extremely confident"]},
            {"id": "Q54", "text": "How often are you given tasks that help you expand your abilities?",
             "options": ["Never","Rarely","Sometimes","Often","Very Often"]},
            {"id": "Q55", "text": "How helpful does your manager provide the feedback or guidance for your growth?",
             "options": ["Not helpful at all","Slightly helpful","Moderately helpful","Very helpful","Extremely helpful"]},
            {"id": "Q56", "text": "How transparent are internal job openings or transfer opportunities?",
             "options": ["Not transparent at all","Slightly transparent","Moderately transparent","Very transparent","Extremely transparent"]},
            {"id": "Q57", "text": "How frequently do you receive constructive feedback about your work?",
             "options": ["Never","Rarely","Sometimes","Often","Very Often"]},
            {"id": "Q58", "text": "How comfortable are you seeking advice or guidance when needed?",
             "options": ["Very uncomfortable","Uncomfortable","Neutral","Comfortable","Very comfortable"]},
            {"id": "Q59", "text": "How fairly are learning and growth opportunities distributed in your workplace?",
             "options": ["Very unfairly","Unfairly","Neutral","Fairly","Very fairly"]},
            {"id": "Q60", "text": "Do you believe employees receive equal chances for development regardless of favoritism or bias?",
             "options": ["Strongly No","No","Neutral","Yes","Strongly Yes"]},
            {"id": "Q61", "text": "How confident are you that your current experience makes you professionally competitive?",
             "options": ["Not confident at all","Slightly confident","Moderately confident","Very confident","Extremely confident"]},
        ],
    },
    {
        "section": "5. Manager & Team Relationship",
        "description": "Your relationship with your manager and team.",
        "items": [
            {"id": "Q62", "text": "How much do you trust your manager to make fair and responsible decisions?",
             "options": ["Do not trust at all","Slightly trust","Moderately trust","Strongly trust","Trust completely"]},
            {"id": "Q63", "text": "How clearly are work expectations and responsibilities communicated to you?",
             "options": ["Very unclear","Unclear","Moderately clear","Clear","Very clear"]},
            {"id": "Q64", "text": "How safe do you feel expressing concerns or opinions at work?",
             "options": ["Not safe at all","Slightly safe","Moderately safe","Very safe","Completely safe"]},
            {"id": "Q65", "text": "Do you feel comfortable admitting mistakes or asking questions within your team?",
             "options": ["Very uncomfortable","Uncomfortable","Neutral","Comfortable","Very comfortable"]},
            {"id": "Q66", "text": "How often do you observe favouritism or unfair treatment at work?",
             "options": ["Never","Rarely","Sometimes","Often","Very Often"]},
            {"id": "Q67", "text": "How available is your manager when you need help or guidance?",
             "options": ["Not available at all","Slightly available","Moderately available","Very available","Extremely available"]},
            {"id": "Q68", "text": "How comfortable are you discussing performance concerns with your manager?",
             "options": ["Very uncomfortable","Uncomfortable","Neutral","Comfortable","Very comfortable"]},
            {"id": "Q69", "text": "How effectively are conflicts or disagreements handled within your team?",
             "options": ["Very poorly","Poorly","Moderately","Effectively","Very effectively"]},
            {"id": "Q70", "text": "How connected do you feel to your team?",
             "options": ["Not connected at all","Slightly connected","Moderately connected","Very connected","Extremely connected"]},
            {"id": "Q71", "text": "How clearly do you understand your responsibilities within the team?",
             "options": ["Very unclear","Unclear","Moderately clear","Clear","Very clear"]},
            {"id": "Q72", "text": "How often do unclear expectations create confusion in your work?",
             "options": ["Never","Rarely","Sometimes","Often","Very Often"]},
        ],
    },
    {
        "section": "6. Fairness & Discrimination",
        "description": "Fairness, inclusion, and respect at your workplace.",
        "items": [
            {"id": "Q73", "text": "How often do you feel employees are underpaid relative to their responsibilities?",
             "options": ["Never","Rarely","Sometimes","Often","Very Often"]},
            {"id": "Q74", "text": "How often do you feel excluded from opportunities that could help your growth?",
             "options": ["Never","Rarely","Sometimes","Often","Very Often"]},
            {"id": "Q75", "text": "Do you believe factors such as personal relationships, gender, age, caste, or seniority influence decisions unfairly?",
             "options": ["Strongly No","No","Neutral","Yes","Strongly Yes"]},
            {"id": "Q76", "text": "How often do you experience dismissive, rude, or disrespectful behavior at work?",
             "options": ["Never","Rarely","Sometimes","Often","Very Often"]},
            {"id": "Q77", "text": "How satisfied are you with the level of dignity and professionalism in the workplace?",
             "options": ["Very dissatisfied","Dissatisfied","Neutral","Satisfied","Very satisfied"]},
            {"id": "Q78", "text": "How connected do you feel to the culture and people in your workplace?",
             "options": ["Not connected at all","Slightly connected","Moderately connected","Very connected","Extremely connected"]},
            {"id": "Q79", "text": "How safe do you feel from harassment, intimidation, or hostile behavior at work?",
             "options": ["Not safe at all","Slightly safe","Moderately safe","Very safe","Completely safe"]},
            {"id": "Q80", "text": "How fairly are workplace rules and policies applied across employees?",
             "options": ["Very unfairly","Unfairly","Neutral","Fairly","Very fairly"]},
            {"id": "Q81", "text": "How often do you observe underrepresentation of certain groups in decision-making roles?",
             "options": ["Never","Rarely","Sometimes","Often","Very Often"]},
        ],
    },
    {
        "section": "7. Trust in Leadership & Culture",
        "description": "Trust in leadership and alignment with organizational culture.",
        "items": [
            {"id": "Q82", "text": "How competent do you perceive the leadership team to be?",
             "options": ["Not competent at all","Slightly competent","Moderately competent","Very competent","Highly competent"]},
            {"id": "Q83", "text": "How often do leadership actions match what was previously communicated?",
             "options": ["Never","Rarely","Sometimes","Often","Very Often"]},
            {"id": "Q84", "text": "How often do leaders demonstrate integrity in difficult situations?",
             "options": ["Never","Rarely","Sometimes","Often","Very Often"]},
            {"id": "Q85", "text": "How aligned are your personal values with the culture of the organization?",
             "options": ["Not aligned at all","Slightly aligned","Moderately aligned","Very aligned","Completely aligned"]},
            {"id": "Q86", "text": "How much do you trust leadership during periods of organizational change or uncertainty?",
             "options": ["Do not trust at all","Slightly trust","Moderately trust","Strongly trust","Trust completely"]},
        ],
    },
    {
        "section": "8. Retention Intent",
        "description": "Your intent to stay or leave the organization.",
        "items": [
            {"id": "Q87", "text": "How often do you think positively about continuing your career here?",
             "options": ["Never","Rarely","Sometimes","Often","Very Often"]},
            {"id": "Q88", "text": "How likely are you to leave this organization within the next year?",
             "options": ["Very unlikely","Unlikely","Neutral","Likely","Very likely"]},
            {"id": "Q89", "text": "How dissatisfied would you need to feel before deciding to leave?",
             "options": ["Slightly dissatisfied","Mildly dissatisfied","Moderately dissatisfied","Very dissatisfied","Extremely dissatisfied"]},
            {"id": "Q90", "text": "Do you currently feel there are unresolved workplace problems affecting your willingness to stay?",
             "options": ["Strongly No","No","Neutral","Yes","Strongly Yes"]},
            {"id": "Q91", "text": "How difficult would it feel emotionally to leave this organization?",
             "options": ["Not difficult at all","Slightly difficult","Moderately difficult","Very difficult","Extremely difficult"]},
            {"id": "Q92", "text": "How attractive do outside job opportunities currently seem to you?",
             "options": ["Not attractive at all","Slightly attractive","Moderately attractive","Very attractive","Extremely attractive"]},
            {"id": "Q93", "text": "How often do you look at job openings outside your organization?",
             "options": ["Never","Rarely","Sometimes","Often","Very Often"]},
            {"id": "Q94", "text": "How likely are you to apply for another job if a suitable opportunity appears?",
             "options": ["Very unlikely","Unlikely","Neutral","Likely","Very likely"]},
            {"id": "Q95", "text": "Would certain workplace improvements make you more likely to stay long term?",
             "options": ["No","Probably No","Unsure","Probably Yes","Yes"]},
        ],
    },
]


# Scoring rubric: each subdomain with items, low/medium/high thresholds (inclusive ranges)
SCORING_RUBRIC = [
    # 1. WELL-BEING & STRESS
    {"domain": "Well-being & Stress", "subdomain": "Perceived Stress", "items": [1,2,3],
     "thresholds": {"low": (3,7), "medium": (8,11), "high": (12,15)}},
    {"domain": "Well-being & Stress", "subdomain": "Burnout / Emotional Exhaustion", "items": [4,5],
     "thresholds": {"low": (2,4), "medium": (5,7), "high": (8,10)}},
    {"domain": "Well-being & Stress", "subdomain": "Workload Burden", "items": [6,7],
     "thresholds": {"low": (2,4), "medium": (5,7), "high": (8,10)}},
    {"domain": "Well-being & Stress", "subdomain": "Work-Life Balance", "items": [8],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Well-being & Stress", "subdomain": "Recovery and Rest", "items": [9],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Well-being & Stress", "subdomain": "Energy and Vitality", "items": [10],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Well-being & Stress", "subdomain": "Coping and Resilience", "items": [11,12],
     "thresholds": {"low": (2,4), "medium": (5,7), "high": (8,10)}},
    {"domain": "Well-being & Stress", "subdomain": "Sleep-Related Impact", "items": [13,14],
     "thresholds": {"low": (2,4), "medium": (5,7), "high": (8,10)}},
    {"domain": "Well-being & Stress", "subdomain": "Wellness Support Access", "items": [15,16,17],
     "thresholds": {"low": (3,7), "medium": (8,11), "high": (12,15)}},

    # 2. JOB SATISFACTION
    {"domain": "Job Satisfaction", "subdomain": "Meaningfulness of Work", "items": [18,19],
     "thresholds": {"low": (2,4), "medium": (5,7), "high": (8,10)}},
    {"domain": "Job Satisfaction", "subdomain": "Compensation Satisfaction", "items": [20,21],
     "thresholds": {"low": (2,4), "medium": (5,7), "high": (8,10)}},
    {"domain": "Job Satisfaction", "subdomain": "Recognition and Appreciation", "items": [22,23],
     "thresholds": {"low": (2,4), "medium": (5,7), "high": (8,10)}},
    {"domain": "Job Satisfaction", "subdomain": "Role Fit and Skill Utilization", "items": [24,25,26],
     "thresholds": {"low": (3,7), "medium": (8,11), "high": (12,15)}},
    {"domain": "Job Satisfaction", "subdomain": "Work Environment Satisfaction", "items": [27],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Job Satisfaction", "subdomain": "Team Relationships", "items": [28,29],
     "thresholds": {"low": (2,4), "medium": (5,7), "high": (8,10)}},
    {"domain": "Job Satisfaction", "subdomain": "Manager Support", "items": [30,31],
     "thresholds": {"low": (2,4), "medium": (5,7), "high": (8,10)}},
    {"domain": "Job Satisfaction", "subdomain": "Job Autonomy", "items": [32,33],
     "thresholds": {"low": (2,4), "medium": (5,7), "high": (8,10)}},
    {"domain": "Job Satisfaction", "subdomain": "Career Growth Satisfaction", "items": [34,35,36],
     "thresholds": {"low": (3,7), "medium": (8,11), "high": (12,15)}},

    # 3. ENGAGEMENT & MOTIVATION
    {"domain": "Engagement & Motivation", "subdomain": "Task Engagement", "items": [37],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Engagement & Motivation", "subdomain": "Goal Commitment", "items": [38,39],
     "thresholds": {"low": (2,4), "medium": (5,7), "high": (8,10)}},
    {"domain": "Engagement & Motivation", "subdomain": "Intrinsic Motivation", "items": [40],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Engagement & Motivation", "subdomain": "Extrinsic Motivation", "items": [41],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Engagement & Motivation", "subdomain": "Initiative and Proactivity", "items": [42,43,44],
     "thresholds": {"low": (3,7), "medium": (8,11), "high": (12,15)}},
    {"domain": "Engagement & Motivation", "subdomain": "Persistence and Effort", "items": [45,46],
     "thresholds": {"low": (2,4), "medium": (5,7), "high": (8,10)}},
    {"domain": "Engagement & Motivation", "subdomain": "Emotional Connection to Work", "items": [47],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Engagement & Motivation", "subdomain": "Voice and Contribution", "items": [48],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Engagement & Motivation", "subdomain": "Purpose Alignment", "items": [49],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},

    # 4. GROWTH & OPPORTUNITY
    {"domain": "Growth & Opportunity", "subdomain": "Learning Opportunities", "items": [50,51,52],
     "thresholds": {"low": (3,7), "medium": (8,11), "high": (12,15)}},
    {"domain": "Growth & Opportunity", "subdomain": "Career Advancement", "items": [53],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Growth & Opportunity", "subdomain": "Challenge and Stretch", "items": [54],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Growth & Opportunity", "subdomain": "Manager Support for Growth", "items": [55],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Growth & Opportunity", "subdomain": "Internal Mobility", "items": [56],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Growth & Opportunity", "subdomain": "Feedback and Coaching", "items": [57,58],
     "thresholds": {"low": (2,4), "medium": (5,7), "high": (8,10)}},
    {"domain": "Growth & Opportunity", "subdomain": "Development Fairness", "items": [59,60],
     "thresholds": {"low": (2,4), "medium": (5,7), "high": (8,10)}},
    {"domain": "Growth & Opportunity", "subdomain": "Future Employability", "items": [61],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},

    # 5. MANAGER & TEAM RELATIONSHIP
    {"domain": "Manager & Team", "subdomain": "Trust in Manager", "items": [62],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Manager & Team", "subdomain": "Communication Quality", "items": [63],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Manager & Team", "subdomain": "Psychological Safety", "items": [64,65],
     "thresholds": {"low": (2,4), "medium": (5,7), "high": (8,10)}},
    {"domain": "Manager & Team", "subdomain": "Respect and Fairness", "items": [66],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Manager & Team", "subdomain": "Support and Availability", "items": [67,68],
     "thresholds": {"low": (2,4), "medium": (5,7), "high": (8,10)}},
    {"domain": "Manager & Team", "subdomain": "Conflict Handling", "items": [69],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Manager & Team", "subdomain": "Team Cohesion", "items": [70],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Manager & Team", "subdomain": "Role Clarity within Team", "items": [71,72],
     "thresholds": {"low": (2,4), "medium": (5,7), "high": (8,10)}},

    # 6. FAIRNESS & DISCRIMINATION
    {"domain": "Fairness & Discrimination", "subdomain": "Pay Equity", "items": [73],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Fairness & Discrimination", "subdomain": "Opportunity Access", "items": [74],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Fairness & Discrimination", "subdomain": "Bias and Favoritism", "items": [75],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Fairness & Discrimination", "subdomain": "Respect and Dignity", "items": [76,77],
     "thresholds": {"low": (2,4), "medium": (5,7), "high": (8,10)}},
    {"domain": "Fairness & Discrimination", "subdomain": "Inclusion and Belonging", "items": [78],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Fairness & Discrimination", "subdomain": "Harassment and Safety", "items": [79],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Fairness & Discrimination", "subdomain": "Policy Fairness", "items": [80],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Fairness & Discrimination", "subdomain": "Representation Fairness", "items": [81],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},

    # 7. TRUST IN LEADERSHIP & CULTURE
    {"domain": "Leadership & Culture", "subdomain": "Leadership Credibility", "items": [82],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Leadership & Culture", "subdomain": "Consistency and Follow-Through", "items": [83],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Leadership & Culture", "subdomain": "Ethical Leadership", "items": [84],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Leadership & Culture", "subdomain": "Value Alignment", "items": [85],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Leadership & Culture", "subdomain": "Change Trust", "items": [86],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},

    # 8. RETENTION INTENT
    {"domain": "Retention Intent", "subdomain": "Stay Commitment", "items": [87],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Retention Intent", "subdomain": "Turnover Intention", "items": [88,89],
     "thresholds": {"low": (2,4), "medium": (5,7), "high": (8,10)}},
    {"domain": "Retention Intent", "subdomain": "Reasons to Stay or Leave", "items": [90],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Retention Intent", "subdomain": "Loyalty and Attachment", "items": [91],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Retention Intent", "subdomain": "Alternative Job Attractiveness", "items": [92],
     "thresholds": {"low": (1,2), "medium": (3,3), "high": (4,5)}},
    {"domain": "Retention Intent", "subdomain": "Risk of Active Job Search", "items": [93,94],
     "thresholds": {"low": (2,4), "medium": (5,7), "high": (8,10)}},
    {"domain": "Retention Intent", "subdomain": "Conditional Retention", "items": [95],
     "thresholds": {"low": (1,1), "medium": (2,2), "high": (3,5)}},
]
